In [5]:
import logging

logging.basicConfig(
    filename="day3.log",
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)
logger = logging.getLogger("internship_day3")
print("Logging configured -> day3.log")

Logging configured -> day3.log

In [6]:
logger.info("Day 3 | Selenium and Beautiful Soup Library")

In [7]:
import pandas as pd

filepath = "data/tiktok.csv"
df = pd.read_csv(filepath)

logger.info("Loaded %s | shape=%s", filepath, df.shape)
print(df.shape)

(df.head(10))

(800, 9)

,Comment ID,Reply to Which Comment,User ID,Comment,Comment Time,Digg Count,Author Digged,Reply Count,Pinned to Top
0,7669319408842081044,NaN,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:21:30 PM",1,Yes,0.0,No
1,7669319064204641044,NaN,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:20:13 PM",1,Yes,0.0,No
2,7669318657889272596,NaN,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:18:36 PM",1,Yes,0.0,No
3,7666354577964712720,NaN,7410829670142657542,❤️❤️❤️,"7/25/2026, 12:36:20 PM",1,Yes,0.0,No
4,7665424955869905685,NaN,6555001822149350400,🙌🙌,"7/23/2026, 12:28:58 AM",1,Yes,1.0,No
5,7665989782560555784,7.665425e+18,7588871257367266322,❣️,"7/24/2026, 1:00:48 PM",0,No,NaN,NaN
6,7665388520731542292,NaN,6989276656456975365,NaN,"7/22/2026, 10:07:37 PM",1,Yes,1.0,No
7,7665389735800472327,7.665389e+18,7588871257367266322,❣️,"7/22/2026, 10:12:16 PM",0,No,NaN,NaN
8,7665382149832917781,NaN,6687364277055161349,mero ni baki xa hoo bro,"7/22/2026, 9:42:58 PM",1,Yes,1.0,No
9,7665389773196870408,7.665382e+18,7588871257367266322,lau lihalnu paryo aba,"7/22/2026, 10:12:27 PM",1,No,NaN,NaN

# checking missing values

In [8]:
print(df.isna().sum())
print((df.isna().mean()*100).round(1))

logger.info("Missing values | %s", (df.isna().mean()*100).round(1))

Comment ID                  0
Reply to Which Comment    431
User ID                     0
Comment                    12
Comment Time                0
Digg Count                  0
Author Digged               0
Reply Count               369
Pinned to Top             369
dtype: int64
Comment ID                 0.0
Reply to Which Comment    53.9
User ID                    0.0
Comment                    1.5
Comment Time               0.0
Digg Count                 0.0
Author Digged              0.0
Reply Count               46.1
Pinned to Top             46.1
dtype: float64

# convert Reply to which Comment to a boolean signal : is_reply

In [9]:
# --- Reply to Which Comment (53.9% missing) ---
# Mechanism: structural (NaN = top-level comment, not a data gap)
# Decision: don't impute a fake ID — convert to a boolean signal
df["is_reply"] = df["Reply to Which Comment"].notna()
print(df.shape)
print(df.isna().sum())

logger.info("Reply to Which Comment | converted to boolean signal 'is_reply'")
df.head(10)

(800, 10)
Comment ID                  0
Reply to Which Comment    431
User ID                     0
Comment                    12
Comment Time                0
Digg Count                  0
Author Digged               0
Reply Count               369
Pinned to Top             369
is_reply                    0
dtype: int64

,Comment ID,Reply to Which Comment,User ID,Comment,Comment Time,Digg Count,Author Digged,Reply Count,Pinned to Top,is_reply
0,7669319408842081044,NaN,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:21:30 PM",1,Yes,0.0,No,False
1,7669319064204641044,NaN,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:20:13 PM",1,Yes,0.0,No,False
2,7669318657889272596,NaN,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:18:36 PM",1,Yes,0.0,No,False
3,7666354577964712720,NaN,7410829670142657542,❤️❤️❤️,"7/25/2026, 12:36:20 PM",1,Yes,0.0,No,False
4,7665424955869905685,NaN,6555001822149350400,🙌🙌,"7/23/2026, 12:28:58 AM",1,Yes,1.0,No,False
5,7665989782560555784,7.665425e+18,7588871257367266322,❣️,"7/24/2026, 1:00:48 PM",0,No,NaN,NaN,True
6,7665388520731542292,NaN,6989276656456975365,NaN,"7/22/2026, 10:07:37 PM",1,Yes,1.0,No,False
7,7665389735800472327,7.665389e+18,7588871257367266322,❣️,"7/22/2026, 10:12:16 PM",0,No,NaN,NaN,True
8,7665382149832917781,NaN,6687364277055161349,mero ni baki xa hoo bro,"7/22/2026, 9:42:58 PM",1,Yes,1.0,No,False
9,7665389773196870408,7.665382e+18,7588871257367266322,lau lihalnu paryo aba,"7/22/2026, 10:12:27 PM",1,No,NaN,NaN,True

# filling missing values of column Reply Count as 0

In [10]:
# --- Reply Count (46.1% missing) ---
# Mechanism: structural (only top-level comments have a reply count)
# Decision: fill with 0 (a reply logically has 0 replies-to-it, tracked elsewhere)
df["Reply Count"] = df["Reply Count"].fillna(0).astype(int)
print(df.shape)
print(df.isna().sum())
logger.info("Reply Count | filled missing with 0 and converted to int")
df.head(10)

(800, 10)
Comment ID                  0
Reply to Which Comment    431
User ID                     0
Comment                    12
Comment Time                0
Digg Count                  0
Author Digged               0
Reply Count                 0
Pinned to Top             369
is_reply                    0
dtype: int64

,Comment ID,Reply to Which Comment,User ID,Comment,Comment Time,Digg Count,Author Digged,Reply Count,Pinned to Top,is_reply
0,7669319408842081044,NaN,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:21:30 PM",1,Yes,0,No,False
1,7669319064204641044,NaN,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:20:13 PM",1,Yes,0,No,False
2,7669318657889272596,NaN,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:18:36 PM",1,Yes,0,No,False
3,7666354577964712720,NaN,7410829670142657542,❤️❤️❤️,"7/25/2026, 12:36:20 PM",1,Yes,0,No,False
4,7665424955869905685,NaN,6555001822149350400,🙌🙌,"7/23/2026, 12:28:58 AM",1,Yes,1,No,False
5,7665989782560555784,7.665425e+18,7588871257367266322,❣️,"7/24/2026, 1:00:48 PM",0,No,0,NaN,True
6,7665388520731542292,NaN,6989276656456975365,NaN,"7/22/2026, 10:07:37 PM",1,Yes,1,No,False
7,7665389735800472327,7.665389e+18,7588871257367266322,❣️,"7/22/2026, 10:12:16 PM",0,No,0,NaN,True
8,7665382149832917781,NaN,6687364277055161349,mero ni baki xa hoo bro,"7/22/2026, 9:42:58 PM",1,Yes,1,No,False
9,7665389773196870408,7.665382e+18,7588871257367266322,lau lihalnu paryo aba,"7/22/2026, 10:12:27 PM",1,No,0,NaN,True

# Pinned to Top filled with Not Applicable

In [11]:
df["Pinned to Top"] = df["Pinned to Top"].fillna("Not Applicable")

print(df["Pinned to Top"].value_counts())
print(df.shape)
print(df.isna().sum()) 
logger.info("Pinned to Top | filled missing with 'Not Applicable'")
df.head(10 )

Pinned to Top
No                431
Not Applicable    369
Name: count, dtype: int64
(800, 10)
Comment ID                  0
Reply to Which Comment    431
User ID                     0
Comment                    12
Comment Time                0
Digg Count                  0
Author Digged               0
Reply Count                 0
Pinned to Top               0
is_reply                    0
dtype: int64

,Comment ID,Reply to Which Comment,User ID,Comment,Comment Time,Digg Count,Author Digged,Reply Count,Pinned to Top,is_reply
0,7669319408842081044,NaN,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:21:30 PM",1,Yes,0,No,False
1,7669319064204641044,NaN,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:20:13 PM",1,Yes,0,No,False
2,7669318657889272596,NaN,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:18:36 PM",1,Yes,0,No,False
3,7666354577964712720,NaN,7410829670142657542,❤️❤️❤️,"7/25/2026, 12:36:20 PM",1,Yes,0,No,False
4,7665424955869905685,NaN,6555001822149350400,🙌🙌,"7/23/2026, 12:28:58 AM",1,Yes,1,No,False
5,7665989782560555784,7.665425e+18,7588871257367266322,❣️,"7/24/2026, 1:00:48 PM",0,No,0,Not Applicable,True
6,7665388520731542292,NaN,6989276656456975365,NaN,"7/22/2026, 10:07:37 PM",1,Yes,1,No,False
7,7665389735800472327,7.665389e+18,7588871257367266322,❣️,"7/22/2026, 10:12:16 PM",0,No,0,Not Applicable,True
8,7665382149832917781,NaN,6687364277055161349,mero ni baki xa hoo bro,"7/22/2026, 9:42:58 PM",1,Yes,1,No,False
9,7665389773196870408,7.665382e+18,7588871257367266322,lau lihalnu paryo aba,"7/22/2026, 10:12:27 PM",1,No,0,Not Applicable,True

# Reply to Which Comment filled with Not Reply to Any Comment

In [12]:
df["Reply to Which Comment"] = df["Reply to Which Comment"].fillna("Not Reply to Any Comment")
logger.info("Reply to Which Comment | filled missing with 'Not Reply to Any Comment'")
print(df.shape)
print(df.isna().sum())
df.head(10 )

(800, 10)
Comment ID                 0
Reply to Which Comment     0
User ID                    0
Comment                   12
Comment Time               0
Digg Count                 0
Author Digged              0
Reply Count                0
Pinned to Top              0
is_reply                   0
dtype: int64

,Comment ID,Reply to Which Comment,User ID,Comment,Comment Time,Digg Count,Author Digged,Reply Count,Pinned to Top,is_reply
0,7669319408842081044,Not Reply to Any Comment,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:21:30 PM",1,Yes,0,No,False
1,7669319064204641044,Not Reply to Any Comment,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:20:13 PM",1,Yes,0,No,False
2,7669318657889272596,Not Reply to Any Comment,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:18:36 PM",1,Yes,0,No,False
3,7666354577964712720,Not Reply to Any Comment,7410829670142657542,❤️❤️❤️,"7/25/2026, 12:36:20 PM",1,Yes,0,No,False
4,7665424955869905685,Not Reply to Any Comment,6555001822149350400,🙌🙌,"7/23/2026, 12:28:58 AM",1,Yes,1,No,False
5,7665989782560555784,7665424955869905920.0,7588871257367266322,❣️,"7/24/2026, 1:00:48 PM",0,No,0,Not Applicable,True
6,7665388520731542292,Not Reply to Any Comment,6989276656456975365,NaN,"7/22/2026, 10:07:37 PM",1,Yes,1,No,False
7,7665389735800472327,7665388520731542528.0,7588871257367266322,❣️,"7/22/2026, 10:12:16 PM",0,No,0,Not Applicable,True
8,7665382149832917781,Not Reply to Any Comment,6687364277055161349,mero ni baki xa hoo bro,"7/22/2026, 9:42:58 PM",1,Yes,1,No,False
9,7665389773196870408,7665382149832918016.0,7588871257367266322,lau lihalnu paryo aba,"7/22/2026, 10:12:27 PM",1,No,0,Not Applicable,True

# Dropping the missing row with no comment

In [ ]:

df = df.dropna(subset=["Comment"])
print(df.isna().sum()) 
print(df.shape)
logger.info("rows with missing 'Comment' dropped | shape=%s", df.shape)
df.head(20)

Comment ID                0
Reply to Which Comment    0
User ID                   0
Comment                   0
Comment Time              0
Digg Count                0
Author Digged             0
Reply Count               0
Pinned to Top             0
is_reply                  0
dtype: int64
(788, 10)

,Comment ID,Reply to Which Comment,User ID,Comment,Comment Time,Digg Count,Author Digged,Reply Count,Pinned to Top,is_reply
0,7669319408842081044,Not Reply to Any Comment,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:21:30 PM",1,Yes,0,No,False
1,7669319064204641044,Not Reply to Any Comment,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:20:13 PM",1,Yes,0,No,False
2,7669318657889272596,Not Reply to Any Comment,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:18:36 PM",1,Yes,0,No,False
3,7666354577964712720,Not Reply to Any Comment,7410829670142657542,❤️❤️❤️,"7/25/2026, 12:36:20 PM",1,Yes,0,No,False
4,7665424955869905685,Not Reply to Any Comment,6555001822149350400,🙌🙌,"7/23/2026, 12:28:58 AM",1,Yes,1,No,False
5,7665989782560555784,7665424955869905920.0,7588871257367266322,❣️,"7/24/2026, 1:00:48 PM",0,No,0,Not Applicable,True
7,7665389735800472327,7665388520731542528.0,7588871257367266322,❣️,"7/22/2026, 10:12:16 PM",0,No,0,Not Applicable,True
8,7665382149832917781,Not Reply to Any Comment,6687364277055161349,mero ni baki xa hoo bro,"7/22/2026, 9:42:58 PM",1,Yes,1,No,False
9,7665389773196870408,7665382149832918016.0,7588871257367266322,lau lihalnu paryo aba,"7/22/2026, 10:12:27 PM",1,No,0,Not Applicable,True
10,7670103883570381575,Not Reply to Any Comment,6598121486987591686,म बिदेस मा छु येहा बाट लाइसेन्स रीनो गर्न मिल्दैन,"8/4/2026, 3:05:38 PM",0,No,0,No,False
11,7670094021976916756,Not Reply to Any Comment,7043789851683505157,medical paxe kati din lagxa approve garna,"8/4/2026, 2:27:25 PM",0,No,0,No,False
12,7670500447186387730,Not Reply to Any Comment,7255479054580777989,मिलेन हो,"8/5/2026, 4:44:28 PM",0,No,0,No,False
13,7670081747802931986,Not Reply to Any Comment,6673154273373160454,daju license ko number kasari change garne🥰,"8/4/2026, 1:39:37 PM",0,No,0,No,False
14,7670030772732166920,Not Reply to Any Comment,6801281188831380486,phone number change garnu chai milxa ki mildai...,"8/4/2026, 10:21:54 AM",0,No,1,No,False
15,7670034874158170898,7670030772732167168.0,7588871257367266322,milxa aja video aune cha,"8/4/2026, 10:37:50 AM",1,No,0,Not Applicable,True
16,7669690242404025108,Not Reply to Any Comment,6924118101551367174,sir Maya form kholeko X ki nqi,"8/3/2026, 12:20:36 PM",0,No,0,No,False
17,7665398460938552072,Not Reply to Any Comment,6966962058097542149,k KO hunu medical ma Gaya pachi harako harakoi,"7/22/2026, 10:46:11 PM",1,Yes,4,No,False
18,7667092289931445010,7665398460938552320.0,7588871257367266322,medical ma gayexi dr lai phone garnu hola or o...,"7/27/2026, 12:19:04 PM",0,No,0,Not Applicable,True
19,7667473041442210568,7665398460938552320.0,7060908934949438470,maile bagmati bata vareko Kun office ma Janey ...,"7/28/2026, 12:56:36 PM",0,No,0,Not Applicable,True
20,7667475008553878290,7665398460938552320.0,7588871257367266322,jun office gaye pani hunxa ailey centralized s...,"7/28/2026, 1:04:15 PM",0,No,0,Not Applicable,True

# new column is_emoji added to clarify emoji or text in commment

In [17]:

import emoji  # pip install emoji



def classify(comment):
    if pd.isna(comment):
        return None  # can't classify missing text
    has_emoji = bool(emoji.emoji_list(comment))
    text_only = emoji.replace_emoji(comment, replace="").strip()
    has_text = len(text_only) > 0

    if has_emoji and has_text:
        return "text"      # mixed → counted as text (your rule)
    elif has_emoji:
        return "emoji"     # emoji-only
    else:
        return "text"      # plain text, no emoji

df["is_emoji"] = df["Comment"].apply(classify)

print(df["is_emoji"].value_counts(dropna=False))
print(df.shape)
print(df.isna().sum())
df.head(15)

is_emoji
text     752
emoji     36
Name: count, dtype: int64
(788, 11)
Comment ID                0
Reply to Which Comment    0
User ID                   0
Comment                   0
Comment Time              0
Digg Count                0
Author Digged             0
Reply Count               0
Pinned to Top             0
is_reply                  0
is_emoji                  0
dtype: int64

,Comment ID,Reply to Which Comment,User ID,Comment,Comment Time,Digg Count,Author Digged,Reply Count,Pinned to Top,is_reply,is_emoji
0,7669319408842081044,Not Reply to Any Comment,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:21:30 PM",1,Yes,0,No,False,emoji
1,7669319064204641044,Not Reply to Any Comment,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:20:13 PM",1,Yes,0,No,False,emoji
2,7669318657889272596,Not Reply to Any Comment,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:18:36 PM",1,Yes,0,No,False,emoji
3,7666354577964712720,Not Reply to Any Comment,7410829670142657542,❤️❤️❤️,"7/25/2026, 12:36:20 PM",1,Yes,0,No,False,emoji
4,7665424955869905685,Not Reply to Any Comment,6555001822149350400,🙌🙌,"7/23/2026, 12:28:58 AM",1,Yes,1,No,False,emoji
5,7665989782560555784,7665424955869905920.0,7588871257367266322,❣️,"7/24/2026, 1:00:48 PM",0,No,0,Not Applicable,True,emoji
7,7665389735800472327,7665388520731542528.0,7588871257367266322,❣️,"7/22/2026, 10:12:16 PM",0,No,0,Not Applicable,True,emoji
8,7665382149832917781,Not Reply to Any Comment,6687364277055161349,mero ni baki xa hoo bro,"7/22/2026, 9:42:58 PM",1,Yes,1,No,False,text
9,7665389773196870408,7665382149832918016.0,7588871257367266322,lau lihalnu paryo aba,"7/22/2026, 10:12:27 PM",1,No,0,Not Applicable,True,text
10,7670103883570381575,Not Reply to Any Comment,6598121486987591686,म बिदेस मा छु येहा बाट लाइसेन्स रीनो गर्न मिल्दैन,"8/4/2026, 3:05:38 PM",0,No,0,No,False,text
11,7670094021976916756,Not Reply to Any Comment,7043789851683505157,medical paxe kati din lagxa approve garna,"8/4/2026, 2:27:25 PM",0,No,0,No,False,text
12,7670500447186387730,Not Reply to Any Comment,7255479054580777989,मिलेन हो,"8/5/2026, 4:44:28 PM",0,No,0,No,False,text
13,7670081747802931986,Not Reply to Any Comment,6673154273373160454,daju license ko number kasari change garne🥰,"8/4/2026, 1:39:37 PM",0,No,0,No,False,text
14,7670030772732166920,Not Reply to Any Comment,6801281188831380486,phone number change garnu chai milxa ki mildai...,"8/4/2026, 10:21:54 AM",0,No,1,No,False,text
15,7670034874158170898,7670030772732167168.0,7588871257367266322,milxa aja video aune cha,"8/4/2026, 10:37:50 AM",1,No,0,Not Applicable,True,text

# save clean data in tiktok_clean.csv

In [27]:
df_clean = df.copy()
df_clean.to_csv("data/tiktok_clean.csv", index=False)
logger.info("Cleaned data saved to 'data/tiktok_clean.csv' Shape=%s  %s" , df_clean.shape, df_clean.isna().sum())
df_clean.head(10)

,Comment ID,Reply to Which Comment,User ID,Comment,Comment Time,Digg Count,Author Digged,Reply Count,Pinned to Top,is_reply,is_emoji
0,7669319408842081044,Not Reply to Any Comment,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:21:30 PM",1,Yes,0,No,False,emoji
1,7669319064204641044,Not Reply to Any Comment,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:20:13 PM",1,Yes,0,No,False,emoji
2,7669318657889272596,Not Reply to Any Comment,6602052900607623174,🥰🥰🥰,"8/2/2026, 12:18:36 PM",1,Yes,0,No,False,emoji
3,7666354577964712720,Not Reply to Any Comment,7410829670142657542,❤️❤️❤️,"7/25/2026, 12:36:20 PM",1,Yes,0,No,False,emoji
4,7665424955869905685,Not Reply to Any Comment,6555001822149350400,🙌🙌,"7/23/2026, 12:28:58 AM",1,Yes,1,No,False,emoji
5,7665989782560555784,7665424955869905920.0,7588871257367266322,❣️,"7/24/2026, 1:00:48 PM",0,No,0,Not Applicable,True,emoji
7,7665389735800472327,7665388520731542528.0,7588871257367266322,❣️,"7/22/2026, 10:12:16 PM",0,No,0,Not Applicable,True,emoji
8,7665382149832917781,Not Reply to Any Comment,6687364277055161349,mero ni baki xa hoo bro,"7/22/2026, 9:42:58 PM",1,Yes,1,No,False,text
9,7665389773196870408,7665382149832918016.0,7588871257367266322,lau lihalnu paryo aba,"7/22/2026, 10:12:27 PM",1,No,0,Not Applicable,True,text
10,7670103883570381575,Not Reply to Any Comment,6598121486987591686,म बिदेस मा छु येहा बाट लाइसेन्स रीनो गर्न मिल्दैन,"8/4/2026, 3:05:38 PM",0,No,0,No,False,text

# Beautiful Soup example

pip install beautifulsoup4

In [28]:
from bs4 import BeautifulSoup 
html = """
<html>
<head><title>My Test Page</title></head>
<body>
    <h1>Welcome to Web Scraping</h1>
    <div class="comment">
        <p class="author">Nawaraj</p>
        <p class="text">This is a great tutorial!</p>
    </div>
    <div class="comment">
        <p class="author">Aashish</p>
        <p class="text">Thanks for sharing.</p>
    </div>
    <a href="https://example.com">Visit Example</a>
</body>
</html>
"""

soup = BeautifulSoup(html, "html.parser")

print("Title:", soup.title.text)
print("H1 text:", soup.h1.text)

print("\nAll authors:")
for author in soup.find_all("p", class_="author"):
    print(" -", author.text)

print("\nAll comment texts:")
for text in soup.find_all("p", class_="text"):
    print(" -", text.text)

print("\nLink href:", soup.a["href"])

Title: My Test Page
H1 text: Welcome to Web Scraping

All authors:
 - Nawaraj
 - Aashish

All comment texts:
 - This is a great tutorial!
 - Thanks for sharing.

Link href: https://example.com

# with a real webpage instead of a fixed string

In [31]:
import requests
from bs4 import BeautifulSoup

url = "https://quotes.toscrape.com/"
response = requests.get(url)

print("Status code:", response.status_code)

soup = BeautifulSoup(response.text, "html.parser")

# Each quote is inside a <div class="quote">
quotes = soup.find_all("div", class_="quote")
print(f"Found {len(quotes)} quotes on this page\n")

for q in quotes:
    text = q.find("span", class_="text").text
    author = q.find("small", class_="author").text
    tags = [tag.text for tag in q.find_all("a", class_="tag")]
    print(f"{text}\n— {author}")
    print("Tags:", tags)
    print("-" * 60)

Status code: 200
Found 10 quotes on this page

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
— Albert Einstein
Tags: ['change', 'deep-thoughts', 'thinking', 'world']
------------------------------------------------------------
“It is our choices, Harry, that show what we truly are, far more than our abilities.”
— J.K. Rowling
Tags: ['abilities', 'choices']
------------------------------------------------------------
“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
— Albert Einstein
Tags: ['inspirational', 'life', 'live', 'miracle', 'miracles']
------------------------------------------------------------
“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
— Jane Austen
Tags: ['aliteracy', 'books', 'classic', 'humor']
------------------------------------------------------------
“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”
— Marilyn Monroe
Tags: ['be-yourself', 'inspirational']
------------------------------------------------------------
“Try not to become a man of success. Rather become a man of value.”
— Albert Einstein
Tags: ['adulthood', 'success', 'value']
------------------------------------------------------------
“It is better to be hated for what you are than to be loved for what you are not.”
— André Gide
Tags: ['life', 'love']
------------------------------------------------------------
“I have not failed. I've just found 10,000 ways that won't work.”
— Thomas A. Edison
Tags: ['edison', 'failure', 'inspirational', 'paraphrased']
------------------------------------------------------------
“A woman is like a tea bag; you never know how strong it is until it's in hot water.”
— Eleanor Roosevelt
Tags: ['misattributed-eleanor-roosevelt']
------------------------------------------------------------
“A day without sunshine is like, you know, night.”
— Steve Martin
Tags: ['humor', 'obvious', 'simile']
------------------------------------------------------------

# Selenium Example
## setup: pip install selenium webdriver-manager --google
## pip install webdriver-manager selenium -- firefox

# Basic page load + check title

In [38]:
from selenium import webdriver
from selenium.webdriver.firefox.service import Service
from webdriver_manager.firefox import GeckoDriverManager

service = Service(GeckoDriverManager().install())
driver = webdriver.Firefox(service=service)

driver.get("https://quotes.toscrape.com/js/")
print("Page title:", driver.title)

driver.quit()

Page title: Quotes to Scrape

In [41]:
from selenium import webdriver
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.firefox import GeckoDriverManager

service = Service(GeckoDriverManager().install())
driver = webdriver.Firefox(service=service)

driver.get("https://quotes.toscrape.com/js/")

quotes = driver.find_elements(By.CLASS_NAME, "quote")
print(f"Found {len(quotes)} quotes\n")

for q in quotes[:3]:
    text = q.find_element(By.CLASS_NAME, "text").text
    author = q.find_element(By.CLASS_NAME, "author").text
    print(f"{text}\n— {author}\n")

driver.quit()

Found 10 quotes

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
— Albert Einstein

“It is our choices, Harry, that show what we truly are, far more than our abilities.”
— J.K. Rowling

“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
— Albert Einstein

In [42]:
logger.info("Day 3 | Selenium and Beautiful Soup Library | Completed")